-- https://www.hackerrank.com/challenges/occupations/problem

SET @A1=0,@A2=0,@A3=0,@A4=0;
SELECT MIN(DOCTOR),MIN(PROFESSOR),MIN(SINGER),MIN(ACTOR)
FROM (SELECT CASE
    WHEN OCCUPATION = 'Doctor' THEN (@A1:=@A1+1)
    WHEN OCCUPATION = 'Professor' THEN (@A2:=@A2+1)
    WHEN OCCUPATION = 'Singer' THEN (@A3:=@A3+1)
    WHEN OCCUPATION = 'Actor' THEN (@A4:=@A4+1) END AS RN,
    CASE WHEN OCCUPATION = 'Doctor' THEN NAME END AS DOCTOR,
    CASE WHEN OCCUPATION = 'Professor' THEN NAME END AS PROFESSOR,
    CASE WHEN OCCUPATION = 'Singer' THEN NAME END AS SINGER,
    CASE WHEN OCCUPATION = 'Actor' THEN NAME END AS ACTOR
    FROM OCCUPATIONS ORDER BY NAME) AS ANS
GROUP BY RN