-- https://www.hackerrank.com/challenges/interviews/problem
-- MS SQL

WITH 
    A AS (SELECT CHALLENGE_ID, 
          TOTAL_VIEWS = SUM(TOTAL_VIEWS), 
          TOTAL_UNIQUE_VIEWS = SUM(TOTAL_UNIQUE_VIEWS)
    FROM VIEW_STATS GROUP BY CHALLENGE_ID
    ),
    B AS (SELECT CHALLENGE_ID, 
          TOTAL_SUBMISSIONS = SUM(TOTAL_SUBMISSIONS), 
          TOTAL_ACCEPTED_SUBMISSIONS = SUM(TOTAL_ACCEPTED_SUBMISSIONS)
    FROM SUBMISSION_STATS GROUP BY CHALLENGE_ID
    )

SELECT C1.CONTEST_ID, C1.HACKER_ID, C1.NAME,
    SUM(TOTAL_SUBMISSIONS), SUM(TOTAL_ACCEPTED_SUBMISSIONS), 
    SUM(TOTAL_VIEWS), SUM(TOTAL_UNIQUE_VIEWS)
FROM CONTESTS C1
    INNER JOIN COLLEGES C2 ON C1.CONTEST_ID = C2.CONTEST_ID
    INNER JOIN CHALLENGES C3 ON C3.COLLEGE_ID = C2.COLLEGE_ID
    LEFT JOIN A S1 ON S1.CHALLENGE_ID = C3.CHALLENGE_ID
    LEFT JOIN B S2 ON S2.CHALLENGE_ID = C3.CHALLENGE_ID
GROUP BY C1.CONTEST_ID, C1.HACKER_ID, C1.NAME
HAVING (SUM(TOTAL_SUBMISSIONS)+SUM(TOTAL_ACCEPTED_SUBMISSIONS)+
        SUM(TOTAL_VIEWS)+SUM(TOTAL_UNIQUE_VIEWS)) <> 0
ORDER BY C1.CONTEST_ID;