-- https://www.hackerrank.com/challenges/challenges/problem

WITH DATA AS 
(SELECT C.HACKER_ID AS ID, H.NAME AS NAME, COUNT(C.HACKER_ID) AS COUNTER
FROM CHALLENGES C INNER JOIN HACKERS H ON C.HACKER_ID = H.HACKER_ID
GROUP BY C.HACKER_ID, H.NAME)

SELECT ID, NAME, COUNTER FROM DATA
WHERE COUNTER = (SELECT MAX(COUNTER) FROM DATA)
OR COUNTER IN (SELECT COUNTER FROM DATA GROUP BY COUNTER HAVING COUNT(COUNTER)=1)
ORDER BY COUNTER DESC, ID;